apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-eso-poc
spec:
  project: default
  destination:
    namespace: "default"
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/moolen/argocd-eso-poc.git
    targetRevision: HEAD
    path: "manifests"

