apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret-senarios
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: fakestore
  target:
    name: mysecret
    creationPolicy: Merge
  data:
    - secretKey: AT_TEST_KEY
      remoteRef:
        key: myapikey
